# Generated by Django 4.2.3 on 2025-01-12 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Friendly name or label for the server.', max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('endpoint', models.URLField(blank=True, help_text='For Amazon EC2 or other remote endpoints, store the URL here.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='toolbox.category')),
                ('parent', models.ForeignKey(blank=True, help_text='If this server is a child, link to a parent server.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='toolbox.server')),
            ],
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServerLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(help_text="Type of the log e.g. 'Docker logs', 'Syslog', etc.", max_length=100)),
                ('content', models.TextField(help_text='The actual log content.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='toolbox.server')),
            ],
        ),
        migrations.AddField(
            model_name='server',
            name='tools',
            field=models.ManyToManyField(blank=True, help_text='Tools like Elasticsearch, Docker, MySQL, etc.', to='toolbox.tool'),
        ),
    ]
